[project]
name = "dj-project1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "celery>=5.6.0",
    "django==5.2",
    "django-redis>=6.0.0",
    "eventlet>=0.40.4",
    "requests>=2.32.5",
]
